language: cpp
compiler:
  - gcc
script: make test-either && valgrind --leak-check=full --show-leak-kinds=all --error-exitcode=1 ./test-either -p --order=lexical
matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - valgrind
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

before_install:
    - eval "${MATRIX_EVAL}"
